version: '3.7'

services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8'
    ports:
      - '5432:5432'
    tty: true
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
    command: redis-server --requirepass redis
    tty: true
